# frozen_string_literal: true

# Phase 1 / 3: EXTRACT — dump live topics from the General category into a JSONL file
# for the classifier (script/classify_run.rb) to consume.
#
# Usage:
#   bin/rails runner script/classify_extract.rb
#
# Produces: ckb/general_classify_in.jsonl
#
# Only live topics are extracted (archived topics already sit in dead storage).

require "json"

OUT_PATH = "ckb/general_classify_in.jsonl"
DOWNSTREAM_PATHS = %w[
  ckb/general_classify_out.csv
  ckb/classify_migrate_audit.csv
  ckb/classify_migrate_review_needed.csv
].freeze
MAX_BODY_CHARS = 1500

# Phase 2 artifacts MUST be regenerated together. If a stale CSV from a previous
# run is sitting in ckb/, classify_run.rb's resume mode would skip already-classified
# IDs (treating old results as canonical for the current DB state). Refuse to run
# unless the user has acknowledged the situation.
stale = DOWNSTREAM_PATHS.select { |p| File.exist?(p) }
if stale.any? && !ARGV.include?("--keep-stale")
  warn "ERROR: stale Phase 2 artifacts present:"
  stale.each { |p| warn "    #{p}  (#{File.mtime(p).strftime("%Y-%m-%d %H:%M")})" }
  warn "Either delete them (rm #{stale.join(" ")}) or rerun with --keep-stale"
  warn "to acknowledge that you really want to keep them."
  exit 1
end

general = Category.find_by(name: "General", parent_category_id: nil)
abort "General category not found — run script/recategorize.rb first" unless general

# Exclude category description topics ("About the X category"). They are
# auto-generated by Discourse on category create and contain no real content;
# leftover ones in General come from old categories deleted in step 7 of
# recategorize.rb. Don't waste classifier tokens on them.
description_topic_ids = Category.where.not(topic_id: nil).select(:topic_id)

scope =
  Topic
    .where(category_id: general.id, archived: false, deleted_at: nil, archetype: "regular")
    .where.not(id: description_topic_ids)
    .includes(:tags, :first_post)
    .order(bumped_at: :desc)

# NOTE: We deliberately use .each instead of .find_each here. find_each silently
# discards the order(bumped_at: :desc) and re-orders by id ASC for batching safety.
# General topic count is small (~hundreds), so loading the full set into memory
# preserves "newest first" order in the JSONL — useful when sampling early rows.
topics = scope.to_a
total = topics.size
puts "Extracting #{total} live topics from General (id=#{general.id}) -> #{OUT_PATH}"

File.open(OUT_PATH, "w") do |f|
  topics
    .each
    .with_index(1) do |t, i|
      raw = t.first_post&.raw.to_s
      truncated = raw.length > MAX_BODY_CHARS
      # tags is preloaded — use map(&:name), not pluck (which would re-query, N+1)
      tag_names = t.tags.map(&:name)
      row = {
        id: t.id,
        title: t.title,
        body: raw[0, MAX_BODY_CHARS],
        body_truncated: truncated,
        reply_count: (t.posts_count - 1).clamp(0, nil),
        created_at: t.created_at&.iso8601,
        bumped_at: t.bumped_at&.iso8601,
        tags: tag_names,
        lang: tag_names.find { |n| n.start_with?("lang-") },
      }
      f.puts row.to_json

      if (i % 50).zero? || i == total
        print "\r  extracted #{i}/#{total}"
        $stdout.flush
      end
    end
end
puts ""
puts "Done. Review first few lines:"
puts File.open(OUT_PATH, &:readline)
